BookKeeping.Web/Models/Domain/Operation.cs
namespace BookKeeping.Web.Models.Domain
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    ///  Operation
    /// </summary>
    public class Operation
    {
        /// <summary>
        /// Identifier
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Operation category
        /// </summary>
        [Required]        
        public virtual OperationCategory Category { get; set; }

        /// <summary>
        /// Owner of operation
        /// </summary>
        public virtual UserProfile UserProfile { get; set; }

        /// <summary>
        /// Date and time of operation
        /// </summary>
        [Required]
        public DateTime DateTime { get; set; }

        /// <summary>
        /// Value
        /// </summary>
        [Required]
        public decimal Value { get; set; }

        /// <summary>
        /// Comment for operation
        /// </summary>
        public string Comment { get; set; }                                
    }
}

BookKeeping.Web/Controllers/OperationController.cs
namespace BookKeeping.Web.Controllers
{
    using System;
    using System.Collections.Generic;    
    using System.Linq;    
    using System.Web.Mvc;

    using BookKeeping.Web.Components.Notifier.Model;
    using BookKeeping.Web.Filters;
    using BookKeeping.Web.Models.DAL;
    using BookKeeping.Web.Models.Domain;
    using BookKeeping.Web.Models.Services;
    using BookKeeping.Web.ViewModel;
    using BookKeeping.Web.ViewModel.Operation;

    /// <summary>
    /// Operation controller
    /// </summary>
    [Authorize]
    public class OperationController : Controller
    {
        private const int NumberRowsOnPage = 10;

        private readonly IAccountService accountService;
        private readonly INotifier notifier;
        private readonly IOperationService operationService;

        private readonly DbContextProvider dbContextProvider;

        /// <summary>
        /// Initialize a new instance of <see cref="OperationController"/> class
        /// </summary>
        /// <param name="accountService">Account service</param>
        /// <param name="notifier">Notifier</param>
        /// <param name="operationService">Operation service</param>
        /// <param name="dbContextProvider">Data context provider</param>
        public OperationController(IAccountService accountService, INotifier notifier, IOperationService operationService, DbContextProvider dbContextProvider)
        {
            this.accountService = accountService;
            this.notifier = notifier;
            this.operationService = operationService;
            this.dbContextProvider = dbContextProvider;
        }

        /// <summary>
        /// Operations list page
        /// </summary>
        /// <returns><see cref="ActionResult"/></returns>
        public ActionResult Index()
        {
            var viewModel = new OperationListViewModel();
            
            return this.View(viewModel);
        }

        /// <summary>
        /// Add operation dialog
        /// </summary>
        /// <returns><see cref="ActionResult"/></returns>
        [NoCache]
        public ActionResult Add()
        {
            var viewModel = new OperationViewModel();
            viewModel.DateTime = DateTime.Now.ToShortDateString();
            return this.PartialView(viewModel);
        }

        /// <summary>
        /// Save new operation action
        /// </summary>
        /// <param name="newOperationViewModel">New operation view model</param>
        /// <returns><see cref="JsonResult"/></returns>
        public JsonResult SaveNew(OperationViewModel newOperationViewModel)
        {
            using (var dbContext = this.dbContextProvider.Init())
            {
                var currentUser = this.accountService.GetCurrentUser();

                currentUser.CreateNewOperation(
                    newOperationViewModel.CategoryName,
                    newOperationViewModel.Value,
                    DateTime.Parse(newOperationViewModel.DateTime),
                    newOperationViewModel.Comment);

                dbContext.SaveChanges();
                return this.Json(new { success = true });
            }
        }

        /// <summary>
        /// Get all category of operations for current user
        /// </summary>
        /// <returns><see cref="JsonResult"/></returns>
        [NoCache]
        public JsonResult GetAllCategoryOperation()
        {
            using (this.dbContextProvider.Init())
            {
                var currentUser = this.accountService.GetCurrentUser();
                return
                    this.Json(
                        currentUser.OperationCategories.Select(p => new { @value = p.Title }).OrderBy(p => p.value),
                        JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Get one page of operations
        /// </summary>
        /// <param name="filter">Filter for list</param>
        /// <param name="pageNumber">Page number</param>
        /// <returns><see cref="JsonResult"/></returns>
        public JsonResult List(OperationFilter filter, int pageNumber)
        {
            using (this.dbContextProvider.Init())
            {
                var operationsQuery = this.operationService.GetListOfOperationsForCurrentUser(filter);
                operationsQuery = operationsQuery.OrderByDescending(p => p.DateTime);

                var resut = new OperationListViewModel
                                {
                                    Paging =
                                        new PagingData
                                            {
                                                PageNumber = pageNumber,
                                                TotalCount = operationsQuery.Count()
                                            }
                                };

                if (resut.Paging.TotalCount > 0)
                {
                    resut.Data =
                        operationsQuery.Skip((resut.Paging.PageNumber - 1) * NumberRowsOnPage)
                            .Take(NumberRowsOnPage)
                            .Select(CreateViewModel())
                            .ToList();
                }
                else
                {
                    resut.Data = new List<OperationViewModel>();
                }

                return this.Json(resut);
            }
        }

        /// <summary>
        /// Delete operations
        /// </summary>
        /// <param name="id">Collection of identifiers of removing operaitions</param>
        /// <returns><see cref="JsonResult"/></returns>
        public JsonResult Delete(IEnumerable<int> id)
        {
            using (var dbContext = this.dbContextProvider.Init())
            {
                this.operationService.RemoveOperations(id);
                this.notifier.Information("Operations removed");
                dbContext.SaveChanges();
                return this.Json(null);
            }
        }

        private static Func<Operation, OperationViewModel> CreateViewModel()
        {
            return
                p =>
                new OperationViewModel
                    {
                        CategoryName = p.Category.Title,
                        Comment = p.Comment,
                        DateTime = p.DateTime.ToShortDateString(),
                        Id = p.Id,
                        Value = p.Value
                    };
        }
    }
}

BookKeeping.Web/Views/Operation/Add.cshtml
@model BookKeeping.Web.ViewModel.Operation.OperationViewModel

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Add new operation</h4>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("SaveNew", "Operation", FormMethod.Post, new { id = "addOperationForm", ajaxForm = "True" }))
            {
                @Html.EditorFor(p => p)                 
            }
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" id="btnSubmitAdd" >Save</button>
        </div>
    </div>
</div>

<script type="text/javascript">       
    $(document).ready(function () {
        
        $.validator.unobtrusive.parse("#addOperationForm");
                
        $('#btnSubmitAdd').click(function () {
            $('#addOperationForm').submit();            
        });

        $('#addModalDialog').on('hidden.bs.modal', function (e) {
            resetForm($('#addOperationForm'));
        });

        $('#addOperationForm').on("ajaxFormSubmitComplete", function() {
            resetForm($('#addOperationForm'));
            $(this).trigger('operationAdded');
            $('#addModalDialog').modal('hide');
        });
        
        function resetForm($form) {
            $form.find('input:text, input:password, input:file, select, textarea').not('#DateTime').val('');
            $form.find('input:radio, input:checkbox')
                 .removeAttr('checked').removeAttr('selected');

            // Reinit category selector to display the newly added categories
            $('#CategoryName').typeahead('destroy');
            $('#CategoryName').typeahead({
                prefetch: '@Url.Action("GetAllCategoryOperation", "Operation")',
                  limit: 10
              });
        }
    });
</script>

BookKeeping.Web/Views/Operation/Index.cshtml
@model BookKeeping.Web.ViewModel.Operation.OperationListViewModel

<div class="row">
    
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body form-inline">
                <div class="form-group">
                    <label for="monthFilter">Month</label>
                    <span id="monthFilter" class="monthpicker" data-bind="monthpicker: filter.month"></span>
                </div>
                <div class="form-group">
                    <label for="categoryFilter">Category</label>
                    <input id="categoryFilter" type="text" class="form-control" placeholder="Category starts with..." data-bind="value: filter.categoryStartsWith, valueUpdate: 'afterkeydown'">
                </div>
            </div>
        </div>
        <table class="table table-hover table-bordered" data-bind="visible: rows().length > 0">
            <thead>
                <tr>
                    <th class="td-checkbox">
                        <input type="checkbox" data-bind="checked: selectedAll" />
                    </th>
                    <th>Date</th>
                    <th>Value</th>
                    <th>Category</th>
                    <th>Comment</th>
                </tr>
            </thead>
            <tbody data-bind="foreach: rows">
                <tr>
                    <td>
                        <input type="checkbox" data-bind="checked: selected" />
                    </td>
                    <td data-bind="text: DateTime"></td>
                    <td data-bind="text: Value"></td>
                    <td data-bind="text: CategoryName"></td>
                    <td data-bind="text: Comment"></td>
                </tr>
            </tbody>
        </table>
        <div class="panel" data-bind="visible: rows().length == 0">
            <div class="panel-body">
                No data found
            </div>
        </div>


        <div class="row">
            <div class="col-md-5">
                <p>
                    <a class="btn btn-primary" data-toggle="modal" href="@Url.Action("Add")" data-target="#addModalDialog">Add</a>
                    <a class="btn btn-default" data-bind="enable: hasSelectedRows, click: deleteSelected">Delete</a>
                </p>
            </div>
            <div class="col-md-7">
                <ul id="operationPager" class="pagination pull-right" data-bind="visible: paging.TotalPagesCount() > 0">
                    <li data-bind="css: { disabled: paging.PageNumber() <= 1 }">
                        <a href="#" data-bind="click: paging.back">&laquo;</a>
                    </li>
                    <!-- ko foreach: paging.pages -->
                    <li data-bind="css: { active: $root.paging.PageNumber() == $data }">
                        <a href="#" data-bind="text: $data, click: $root.paging.selectPage"></a>
                    </li>
                    <!-- /ko -->
                    <li data-bind="css: { disabled: paging.PageNumber() >= paging.TotalPagesCount() }">
                        <a href="#" data-bind="click: paging.next">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="addModalDialog" class="modal fade">
</div>


<script type="text/javascript">
    $(document).ready(function () {
        var initData =  @Html.ToJson(Model);
        var operationListViewModel = function() {
            var self = this;
            self.pagingInitData = initData.Paging;
            self.filter = {
                month: ko.observable(new Date(parseInt(initData.Filter.Month.replace(/\/Date\((.*?)\)\//gi, "$1")))),
                categoryStartsWith: ko.observable(initData.Filter.CategoryStartsWith)
            };

            window.bookkeeping.AddGridViewMixin(self, '@Url.Action("List")', '@Url.Action("Delete")');
        };

        var viewModel = new operationListViewModel();
        ko.applyBindings(viewModel);

        $('#addModalDialog').on('operationAdded', function() {            
            viewModel.reload();
        });
    });
</script>